import { useState, useEffect, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Calendar } from "@/components/ui/calendar";
import { Plus } from "lucide-react";
import { format } from "date-fns";
import axios from "axios";
import { useAuth } from "@/context/AuthContext";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Separator } from "@/components/ui/separator";

// const API_BASE_URL = "http://localhost:3001";
import { API_BASE_URL } from '@/config/api'; // Import the centralized API URL

export function AddAssetDialog({
  fetchAssets,
  departments,
  categories,
  subCategories,
  assets = [], // Add assets as a prop with default empty array
}) {
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  const [itemCode, setItemCode] = useState("");
  const [dateAcquired, setDateAcquired] = useState(null);
  const [serialNo, setSerialNo] = useState("");
  const [unitPrice, setUnitPrice] = useState("");
  const [description, setDescription] = useState("");
  const [supplier, setSupplier] = useState("");
  const [selectedDepartmentId, setSelectedDepartmentId] = useState("");
  const [selectedCategoryId, setSelectedCategoryId] = useState("");
  const [selectedSubCategoryId, setSelectedSubCategoryId] = useState("");
  const [isItemCodeAutoGenerated, setIsItemCodeAutoGenerated] = useState(false);

  // Filter categories (no department filtering needed since categories are independent of departments)
  const filteredCategories = categories;

  // Filter sub-categories based on selected category
  const filteredSubCategories = useMemo(() => {
    if (!selectedCategoryId) return [];
    
    return subCategories.filter(
      (subCat) => subCat.category_id.toString() === selectedCategoryId
    );
  }, [subCategories, selectedCategoryId]);

  // Function to generate item code based on department and sub-category
  const generateItemCode = (deptId, subCatId) => {
    if (!deptId || !subCatId) return "";
    
    // Find department and sub-category names
    const department = departments.find(dept => dept.id.toString() === deptId);
    const subCategory = subCategories.find(subCat => subCat.id.toString() === subCatId);
    
    if (!department || !subCategory) return "";
    
    // Create base code from department and full sub-category name
    const deptCode = department.name.substring(0, 3).toUpperCase();
    const subCatCode = subCategory.name.replace(/\s+/g, ''); // Remove spaces
    const baseCode = `${deptCode}${subCatCode}-`;
    
    // Find assets with similar item codes
    const similarCodes = assets
      .filter(asset => asset.item_code && asset.item_code.startsWith(baseCode))
      .map(asset => asset.item_code);
    
    // Extract numbers from similar codes and find the highest
    let maxNumber = 0;
    similarCodes.forEach(code => {
      const numberPart = code.replace(baseCode, '');
      const number = parseInt(numberPart) || 0;
      if (number > maxNumber) {
        maxNumber = number;
      }
    });
    
    // Generate next number
    const nextNumber = maxNumber + 1;
    return `${baseCode}${nextNumber}`;
  };

  // Effect to auto-generate item code when department and sub-category are selected
  useEffect(() => {
    if (selectedDepartmentId && selectedSubCategoryId) {
      const newCode = generateItemCode(selectedDepartmentId, selectedSubCategoryId);
      if (newCode) {
        setItemCode(newCode);
        setIsItemCodeAutoGenerated(true);
      }
    } else if (!selectedDepartmentId || !selectedSubCategoryId) {
      // Clear item code if either selection is cleared
      setItemCode("");
      setIsItemCodeAutoGenerated(false);
    }
  }, [selectedDepartmentId, selectedSubCategoryId]);

  useEffect(() => {
    setSelectedCategoryId("");
    setSelectedSubCategoryId("");
  }, [selectedDepartmentId]);

  useEffect(() => {
    setSelectedSubCategoryId("");
  }, [selectedCategoryId]);

  const handleConfirm = async () => {
    if (
      itemCode.trim() &&
      dateAcquired &&
      serialNo.trim() &&
      unitPrice &&
      description.trim() &&
      supplier.trim() &&
      selectedSubCategoryId &&
      selectedDepartmentId
    ) {
      try {
        await axios.post(
          `${API_BASE_URL}/assets`,
          {
            item_code: itemCode.trim(),
            date_acquired:
              dateAcquired instanceof Date
                ? format(dateAcquired, "yyyy-MM-dd")
                : dateAcquired,
            serial_no: serialNo.trim(),
            unit_price: parseFloat(unitPrice),
            description: description.trim(),
            supplier: supplier.trim(),
            sub_category_id: parseInt(selectedSubCategoryId),
            department_id: parseInt(selectedDepartmentId),
          },
          { headers: { Authorization: `Bearer ${user.token}` } }
        );
        fetchAssets();
        setOpen(false);
        setItemCode("");
        setDateAcquired(null);
        setSerialNo("");
        setUnitPrice("");
        setDescription("");
        setSupplier("");
        setSelectedDepartmentId("");
        setSelectedCategoryId("");
        setSelectedSubCategoryId("");
        setIsItemCodeAutoGenerated(false);
        alert("Add Successful");
      } catch (error) {
        console.error("Error adding asset:", error);
        alert("Failed to add asset.");
      }
    }
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => {
      setOpen(isOpen);
      if (!isOpen) {
        // Reset form when dialog is closed
        setItemCode("");
        setDateAcquired(null);
        setSerialNo("");
        setUnitPrice("");
        setDescription("");
        setSupplier("");
        setSelectedDepartmentId("");
        setSelectedCategoryId("");
        setSelectedSubCategoryId("");
        setIsItemCodeAutoGenerated(false);
      }
    }}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" />
          ADD ASSET
        </Button>
      </DialogTrigger>
      
      <DialogContent className="sm:max-w-[600px] max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Add Asset</DialogTitle>
          <DialogDescription>
            Enter the details for the new asset.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Classification Section */}
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold">Classification</h3>
              <p className="text-sm text-gray-500">Categorize this asset</p>
            </div>
            
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="department">Department</Label>
                <Select 
                  value={selectedDepartmentId} 
                  onValueChange={setSelectedDepartmentId}
                  disabled={!departments.length}
                >
                  <SelectTrigger id="department">
                    <SelectValue placeholder="Select department" />
                  </SelectTrigger>
                  <SelectContent>
                    {departments
                      .filter((dept) => dept.status === "Active")
                      .map((dept) => (
                        <SelectItem key={dept.id} value={dept.id.toString()}>
                          {dept.name}
                        </SelectItem>
                      ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="category">Category</Label>
                <Select
                  value={selectedCategoryId}
                  onValueChange={setSelectedCategoryId}
                  disabled={!categories.length}
                >
                  <SelectTrigger id="category">
                    <SelectValue placeholder="Select category" />
                  </SelectTrigger>
                  <SelectContent>
                    {/* Use all categories since they're independent of departments */}
                    {categories.map((cat) => (
                      <SelectItem key={cat.id} value={cat.id.toString()}>
                        {cat.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="subcategory">Sub-Category</Label>
                <Select
                  value={selectedSubCategoryId}
                  onValueChange={setSelectedSubCategoryId}
                  disabled={!selectedCategoryId || !filteredSubCategories.length}
                >
                  <SelectTrigger id="subcategory">
                    <SelectValue placeholder="Select sub-category" />
                  </SelectTrigger>
                  <SelectContent>
                    {filteredSubCategories.map((subCat) => (
                      <SelectItem key={subCat.id} value={subCat.id.toString()}>
                        {subCat.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          <Separator />

          {/* Asset Details Section */}
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold">Asset Details</h3>
              <p className="text-sm text-gray-500">Basic information about the asset</p>
            </div>
            
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="itemCode">Item Code</Label>
                <Input
                  id="itemCode"
                  value={itemCode}
                  onChange={(e) => {
                    setItemCode(e.target.value);
                    setIsItemCodeAutoGenerated(false); // User is manually editing
                  }}
                  placeholder="Auto-generated when department and sub-category are selected"
                  readOnly={isItemCodeAutoGenerated}
                  className={isItemCodeAutoGenerated ? "bg-gray-100 text-gray-500 cursor-not-allowed" : ""}
                />
                {isItemCodeAutoGenerated && (
                  <p className="text-xs text-gray-500">
                    Auto-generated based on department and sub-category.
                  </p>
                )}
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="dateAcquired">Date Acquired</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button 
                      variant="outline" 
                      className="w-full justify-start text-left font-normal"
                      id="dateAcquired"
                    >
                      {dateAcquired ? format(dateAcquired, "PPP") : "Pick a date"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0" align="start">
                    <Calendar 
                      mode="single" 
                      selected={dateAcquired} 
                      onSelect={setDateAcquired}
                      initialFocus
                    />
                  </PopoverContent>
                </Popover>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="serialNo">Serial No.</Label>
                <Input
                  id="serialNo"
                  value={serialNo}
                  onChange={(e) => setSerialNo(e.target.value)}
                  placeholder="Enter serial number"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="unitPrice">Unit Price (PHP)</Label>
                <Input
                  id="unitPrice"
                  type="number"
                  value={unitPrice}
                  onChange={(e) => setUnitPrice(e.target.value)}
                  placeholder="0.00"
                />
              </div>
              
              <div className="space-y-2 sm:col-span-2">
                <Label htmlFor="supplier">Supplier</Label>
                <Input
                  id="supplier"
                  value={supplier}
                  onChange={(e) => setSupplier(e.target.value)}
                  placeholder="Enter supplier name"
                />
              </div>
            </div>
          </div>

          <Separator />

          {/* Description Section */}
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold">Description</h3>
              <p className="text-sm text-gray-500">Additional details about the asset</p>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full min-h-[120px] p-3 border border-gray-300 rounded-md resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Enter asset description"
                maxLength={255}
              />
              <div className="text-sm text-gray-500 flex justify-between">
                <span>Describe the asset in detail</span>
                <span>{description.length}/255 characters</span>
              </div>
            </div>
          </div>
        </div>

        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="outline" className="mr-2" onClick={() => setOpen(false)}>Cancel</Button>
          <Button onClick={handleConfirm}>Add Asset</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
